name: Determine branch name
description: "Given a version, outputs the name of the branch associated with that version. For minor releases, that would be the 'main' branch.  For patch releases, that would be the 'major.minor.x' branch."
inputs:
  version:
    description: The version for which to output the branch
    required: true
outputs:
  branch-name:
    description: The branch name associated with the given version
    value: ${{ steps.determine-branch.outputs.branch-name }}
runs:
  using: composite
  steps:
    - id: determine-branch
      run: |
        BRANCH_NAME=main
        if [[ ${{ !endsWith(inputs.version, '.0') }} ]]; then
          BRANCH_NAME=$(echo ${{ inputs.version }} | sed -r s/^\([0-9]+\.[0-9]+\.\)[0-9]+$/\\1x/)
        fi
        echo "::set-output name=branch-name::$BRANCH_NAME"
      shell: bash
