name: Determine maintenance branch name
description: "Given a version, outputs the name of the maintenance branch associated with that version."
inputs:
  version:
    description: The version for which to output the maintenance branch
    required: true
outputs:
  branch-name:
    description: The maintenance branch name associated with the given version
    value: ${{ steps.determine-branch.outputs.branch-name }}
runs:
  using: composite
  steps:
    - id: determine-branch
      run: |
        BRANCH_NAME=$(echo ${{ inputs.version }} | sed -r s/^\([0-9]+\.[0-9]+\.\)[0-9]+$/\\1x/)
        echo "::set-output name=branch-name::$BRANCH_NAME"
      shell: bash
