name: 'Get last workflow run number'
description: 'Returns the last run number for the specified workflow in the specified branch'
inputs:
  workflow-name:
    description: 'Name of the workflow for which to get the last run number'
    required: true
  branch-name:
    description: 'Name of the branch for which to get the last workflow run number'
    required: true
    default: main
outputs:
  last-run-number:
    description: 'The last run number for the given workflow in the given branch'
    value: ${{ steps.get-last-run-number.outputs.last-run-number }}
runs:
  using: composite
  steps:
    - id: get-last-run-number
      run: |
        API_QUERY="repos/${{ github.repository }}/actions/workflows/.github%2fworkflows%2f${{ inputs.workflow-name }}.yml/runs?per_page=1&branch=${{ inputs.branch-name }}"
        gh api "$API_QUERY" --jq ".workflow_runs[].run_number"
        echo "::set-output name=last-run-number::$RUN_NUMBER"
      shell: bash