name: Application build for Java-based workflows

on:
  workflow_call:
    inputs:
      applicationModule:
        required: true
        type: string
      applicationDirectory:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      dockerUsername:
        required: true
      dockerPassword:
        required: true

env:
  ARTIFACT_ID: ${{ inputs.version }}-gh{{ github.run_number }}

jobs:
  build:
    name: Application Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
      - name: Set up Maven
        uses: ./.github/actions/setup-maven
        with:
          maven-version: 3.8.3
      - name: Maven build for ${{ inputs.applicationDirectory}}/${{ inputs.applicationModule }}
        env:
          MAVEN_OPTS: >-
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
            -Dorg.slf4j.simpleLogger.showDateTime=true
          MAVEN_CLI_OPTS: >-
            --batch-mode --errors --show-version --update-snapshots
        run: |
          mvn $MAVEN_CLI_OPTS install -f pet-parent -pl :${{ inputs.applicationModule }} -am
      - name: Dev artifactory login
        uses: azure/docker-login@v1
        with:
          login-server: dockerhub.com
          username: ${{ secrets.dockerUsername }}
          password: ${{ secrets.dockerPassword }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker build and push
        uses: docker/build-push-action@v2
        env:
          IMAGE_NAME: ncr.nuance.com/xnluaas-docker-dev/${{ inputs.applicationModule }}
        with:
          file: ./Dockerfile
          context: ./${{ inputs.applicationDirectory }}/${{ inputs.applicationModule }}/target/package
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.ARTIFACT_ID }}
          build-args: APPLICATION_NAME=${{ inputs.applicationModule }}
