name: Cat Service

on:
  push:
    paths:
      - cats/** # Everything under cats
      - pet-*parent/**
      - .github/workflows/cat-service.yaml
      - .github/workflows/application-build.yml
      - .github/actions/**
      - Dockerfile

jobs:
  build:
    uses: ./.github/workflows/application-build.yml
    with:
      applicationModule: cat-service
      applicationDirectory: cats
      artifactId: 1.0.0-gh{{ github.run_number }}
      containerRegistryHost: dockerhub.com
      containerRegistryRepository: ci-test
    secrets:
      containerRegistryUsername: DEV_ARTIFACTORY_USERNAME
      containerRegistryPassword: DEV_ARTIFACTORY_PASSWORD