name: Cat Service

on:
  push:
    paths:
      - cats/** # Everything under cats
      - pet-*parent/**
      - .github/workflows/cat-service.yaml
      - .github/workflows/application-build.yml
      - .github/actions/**
      - Dockerfile

jobs:
  build:
    uses: ./.github/workflows/application-build.yml
    with:
      applicationModule: cat-service
      applicationDirectory: cats
      version: 1.0.0
    secrets:
      dockerUsername: DEV_ARTIFACTORY_USERNAME
      dockerPassword: DEV_ARTIFACTORY_PASSWORD