name: Cat Service

on:
  push:
    branches:
      - '**'
    paths:
      - cats/** # Everything under cats
      - pet-*parent/**
      - .github/workflows/cat-service.yml
      - .github/workflows/application-build.yml
      - .github/actions/setup-maven/**
      - Dockerfile

jobs:
  build:
    uses: ./.github/workflows/application-build.yml
    with:
      applicationModule: cat-service
      applicationDirectory: cats
      artifactId: 1.0.0-gh${{ github.run_number }}
      containerRegistryHost: ghcr.io
      containerRegistryRepository: ${{ github.repository_owner }}
#      containerRegistryHost: hub.docker.com
#      containerRegistryRepository: nuancecoretech
    secrets:
      containerRegistryUsername: ${{ github.actor }}
      containerRegistryPassword: ${{ secrets.GITHUB_TOKEN }}
#      containerRegistryUsername: DEV_ARTIFACTORY_USERNAME
#      containerRegistryPassword: DEV_ARTIFACTORY_PASSWORD