name: Pet Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  VERSION: ${{ github.ref_name }}
  PARENT_POM: pet-parent/pom.xml

jobs:
  validate-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate version number
        run: |
          echo Verifying that ${{ env.VERSION }} is the same as parent POM version
          test ${{ env.VERSION }} = $(sed -n -r 's/.+<revision>([0-9]+\.[0-9]+\.[0-9]+)<\/revision>/\1/p' ${{ env.PARENT_POM }})

  last-run-numbers:
    runs-on: ubuntu-latest
    needs: validate-version
    outputs:
      cat-service: ${{ steps.cat-service.outputs.last-run-number }}
    steps:
      - uses: actions/checkout@v2
      - id: cat-service
        name: Get latest cat-service run number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          .github/scripts/output-last-workflow-run-number.sh cat-service ${{ github.repository }}
          
  release-notes:
    runs-on: ubuntu-latest
    needs: last-run-numbers
    steps:
      - name: Generate release notes
        run: |
          echo "These are the release notes" >> release-notes.txt
          echo "Application build numbers in this release:" >> release-notes.txt
          echo "* cat-service: ${{ env.VERSION }}-gh${{ needs.last-run-numbers.outputs.cat-service }}" >> release-notes.txt
      - name: Upload release notes artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-notes
          path: release-notes.txt

  release:
    runs-on: ubuntu-latest
    needs: release-notes
    steps:
      - uses: actions/checkout@v2
      - name: Download release notes artifact
        uses: actions/download-artifact@v3
        with:
          name: release-notes
      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.VERSION }} --notes-file release-notes.txt

  promote:
    runs-on: ubuntu-latest
    needs: last-run-numbers
    steps:
      - name: Promote to ACR
        run: |
          echo "This would be where we would promote the latest builds"
          echo ${{ env.VERSION }}
          echo "Promoting cat-service build ${{ env.VERSION }}-gh${{ needs.last-run-numbers.outputs.cat-service }}"

  maintenance-branch:
    if: endsWith(github.ref_name, '.0') # Only versions on the main branch have no patch version
    runs-on: ubuntu-latest
    needs: validate-version
    steps:
      - uses: actions/checkout@v2
      - name: Create maintenance branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=$(echo ${{ env.VERSION }} | sed -r s/^\([0-9]+\.[0-9]+\.\)[0-9]+$/\\1x/)
          echo Creating maintenance branch $BRANCH_NAME from tag ${{ env.VERSION }}
          git config user.name "GitHub Release Workflow"
          git config user.email "<>"
          .github/scripts/bump-maven-revision.sh ${{ env.VERSION }} patch ${{ env.PARENT_POM }} $BRANCH_NAME

  main-branch-minor-version-bump:
    if: endsWith(github.ref_name, '.0') # Main branch releases result in a minor version number bump
    runs-on: ubuntu-latest
    needs: validate-version
    steps:
      - uses: actions/checkout@v2
      - name: Bump minor version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Release Workflow"
          git config user.email "<>"
          .github/scripts/bump-maven-revision.sh ${{ env.VERSION }} minor ${{ env.PARENT_POM }} feature/bump-main-branch-minor-version
          gh pr create --base main --fill
          gh pr --approve
          gh pr merge --rebase --auto --delete-branch

  maintenance-branch-patch-version-bump:
    if: ${{ !endsWith(github.ref_name, '.0') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump patch version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=$(echo ${{ env.VERSION }} | sed -r s/^\([0-9]+\.[0-9]+\.\)[0-9]+$/\\1x/)
          git config user.name "GitHub Release Workflow"
          git config user.email "<>"
          .github/scripts/bump-maven-revision.sh ${{ env.VERSION }} patch ${{ env.PARENT_POM }} $BRANCH_NAME